[build]
  functions = "functions"

[[redirects]]
  from = "/app"
  to = "/.netlify/functions/app-redirect"
  status = 302
  force = true

[[redirects]]
  from = "/download"
  to = "/.netlify/functions/download"
  status = 302
  force = true
